# Generated by Django 4.0.6 on 2022-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Roupas', 'Roupas'), ('Eletrônicos', 'Eletrônicos'), ('Calçados', 'Calçados'), ('Informática', 'Informática')], max_length=50, null=True),
        ),
    ]
